# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: liquidvisual-boilerplate
dev_mode_enabled: true # LV responsive tool

# Grunt handles images and assets.
exclude: ['img', 'css', 'scripts', 'builder-app/scripts', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess', '_pages']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Docs
collections:
  docs:
    output: true

# https://github.com/jekyll/jekyll-sitemap
# If you would like to exclude specific pages/posts from the sitemap set the sitemap flag to false in the front matter for the page/post.
#
# sitemap: false

gems:
  - jekyll-sitemap