# ---------------------
# GLOBAL SITE SETTINGS
# ---------------------

cname: loadshift.yourwebvisual.com

# META
title: "Loadshift"
seo_title: "Loadshift - Australia's Heavy Haulage Transport Marketplace"
company: "Loadshift"
description: "Loadshift is Australia's Leading Heavy Haulage Transport Marketplace"
github_repo: https://github.com/liquidvisual/loshift-0516 #/blob/master/


# CONTACT
email: contact@loadshift.com.au
phone: 1300 562 374
sms: (02) 4587 7560
fax: (02) 4587 7560
abn: 79003633224

# OFFICES
offices:
  - title: Sydney
    address: "P.O. Box 349<br>Windsor NSW, 2756"

# SOCIAL MEDIA
facebook: "https://www.facebook.com/loadshift/"
youtube: https://www.youtube.com/user/terex4066
google_plus: ""

# GOOGLE
google_map: ""
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  - title: Digital Momentum
    url: http://digitalmomentum.com.au
    logo:
    description: Website by Digital Momentum